PROGRAM TOTREES;

  CONST
    BL = ' ';
    BL2 = '  ';
    DUMMY = '';
  VAR
    PS : CHAR;
    N, COUNTH, COUNTT : LONGINT;
    INP , OUT, OUT1, OUT2 : TEXT;    
    LINE, HEAD0, HEAD, TAIL : STRING [100];

BEGIN
  ASSIGN (INP, 'COORDAL2.TXT');
  RESET (INP);
  WRITELN ('  FILE ', 'COORDAL2.TXT', ' BEING PROCESSED');
 
  ASSIGN (OUT, 'ASSOCIAT.TXT');
  REWRITE (OUT);
  ASSIGN (OUT1, 'ASSOBUSH.TXT');
  REWRITE (OUT1);
  {ASSIGN (OUT2, 'ASSOCIAT.STS');
  REWRITE (OUT2);}
  COUNTH := 0;
  COUNTT := 0;
  HEAD0 := DUMMY;

  REPEAT
    READLN (INP, LINE);
    N := POS (BL2, LINE);
    PS := LINE [N+2];
    HEAD := COPY (LINE, 1, N-1);
    IF HEAD <> HEAD0
      THEN
        BEGIN
          WRITELN (OUT, '+ '+PS+BL, HEAD);
          WRITELN (OUT1, HEAD);
          INC (COUNTH);
          HEAD0 := HEAD;
        END;
    TAIL := COPY (LINE, N+5, LENGTH(LINE)-N-4);
    WRITELN (OUT, '- '+PS+BL, TAIL);
    WRITELN (OUT1, BL2, TAIL);
    INC (COUNTT);
  UNTIL EOF (INP);
  FLUSH (OUT);
  FLUSH (OUT1);

  WRITELN ('  FILE ', 'ASSOCIAT.TXT', ' CONTAINS:');
  WRITELN (COUNTH:6, ' HEADS');
  WRITELN (COUNTT:6, ' ASSOCIATES');
  WRITELN (COUNTT/COUNTH:6:3, ' ASSO/HEAD');
END.
